# Generated by Django 4.1 on 2022-08-07 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=80)),
            ],
            options={"verbose_name": " کشور", "verbose_name_plural": "کشور ها",},
        ),
        migrations.CreateModel(
            name="Days",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.CharField(max_length=40)),
            ],
            options={"verbose_name": "روز", "verbose_name_plural": "روز ها",},
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="ژانر")),
                ("slug", models.SlugField(unique=True, verbose_name="آدرس ژانر")),
            ],
            options={"verbose_name": "ژانر", "verbose_name_plural": "ژانر ها",},
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=80)),
            ],
            options={"verbose_name": "زیان", "verbose_name_plural": "زیان ها",},
        ),
        migrations.CreateModel(
            name="PIN_POST",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="تیتر")),
                (
                    "img",
                    models.ImageField(
                        null=True, upload_to="images/", verbose_name="آدرس عکس"
                    ),
                ),
                ("story", models.TextField(null=True, verbose_name="خلاصه")),
                ("body", models.TextField(null=True, verbose_name="متن")),
                (
                    "published",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("visited", models.IntegerField(verbose_name="بازدید ها")),
                (
                    "active",
                    models.BooleanField(
                        default=False, verbose_name="آیا این پست منتشر شود"
                    ),
                ),
            ],
            options={"verbose_name": "پین", "verbose_name_plural": "پین ها",},
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=40)),
            ],
            options={"verbose_name": "وضعیت", "verbose_name_plural": "وضعیت ها",},
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=40)),
            ],
            options={"verbose_name": "نوع", "verbose_name_plural": "انواع",},
        ),
        migrations.CreateModel(
            name="Year",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=25)),
            ],
            options={"verbose_name": "سال", "verbose_name_plural": "سال ها",},
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="تیتر")),
                ("name", models.CharField(max_length=100, verbose_name="نام")),
                (
                    "episode",
                    models.CharField(
                        max_length=100, null=True, verbose_name="تعداد قسمت ها"
                    ),
                ),
                ("time", models.CharField(max_length=100, verbose_name="زمان")),
                ("visited", models.IntegerField(null=True, verbose_name="بازدید ها")),
                (
                    "director",
                    models.CharField(max_length=80, null=True, verbose_name="کارگردان"),
                ),
                (
                    "actors",
                    models.CharField(
                        max_length=100, null=True, verbose_name="بازیگران"
                    ),
                ),
                (
                    "release",
                    models.CharField(
                        max_length=200, null=True, verbose_name="تاریخ پخش"
                    ),
                ),
                ("story", models.TextField(null=True, verbose_name="خلاصه")),
                (
                    "img",
                    models.ImageField(
                        null=True, upload_to="images/", verbose_name="آدرس عکس"
                    ),
                ),
                (
                    "published",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=False, verbose_name="آیا این پست منتشر شود"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="نویسنده",
                    ),
                ),
                (
                    "category",
                    models.ManyToManyField(to="postapp.genre", verbose_name="ژانر"),
                ),
                (
                    "day",
                    models.ManyToManyField(
                        to="postapp.days", verbose_name="روز های پخش"
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="postapp.language",
                        verbose_name="زبان",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="postapp.country",
                        verbose_name="محصول",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="postapp.state",
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "type_film",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="postapp.type",
                        verbose_name="نوع",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="postapp.year",
                        verbose_name="سال تولید",
                    ),
                ),
            ],
            options={"verbose_name": "پست", "verbose_name_plural": "پست ها",},
        ),
        migrations.CreateModel(
            name="Frame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("episode", models.CharField(max_length=80, verbose_name="اسم لینک")),
                ("frame", models.CharField(max_length=20, verbose_name="کیفیت")),
                ("url", models.URLField(max_length=2000, verbose_name="آدرس")),
                (
                    "post",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="postapp.post",
                        verbose_name="پست",
                    ),
                ),
            ],
            options={
                "verbose_name": "لینک های ایجاد شده",
                "verbose_name_plural": "تمام لینک های ایجاد شده",
            },
        ),
        migrations.CreateModel(
            name="Download",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="لینک")),
                ("active", models.BooleanField(verbose_name="لینک فیلم و سریال")),
                ("order", models.IntegerField()),
                (
                    "frame",
                    models.ManyToManyField(
                        related_name="Frame", to="postapp.frame", verbose_name="کیفیت"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="postapp.post",
                        verbose_name="پست",
                    ),
                ),
            ],
            options={
                "verbose_name": "لینک دانلود",
                "verbose_name_plural": "لینک های دانلود",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="ایمیل")),
                ("name", models.CharField(max_length=50, verbose_name="نام")),
                ("body", models.TextField(verbose_name="دیدگاه")),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "active",
                    models.BooleanField(
                        default=False, verbose_name="آیا این دیدگاه منتشر شود"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Comments",
                        to="postapp.post",
                        verbose_name="پست",
                    ),
                ),
                (
                    "reply",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="postapp.comment",
                        verbose_name="پاسخ ها",
                    ),
                ),
            ],
            options={"verbose_name": "دیدگاه", "verbose_name_plural": "دیدگاه ها",},
        ),
        migrations.CreateModel(
            name="Askformovie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="ایمیل")),
                ("name", models.CharField(max_length=50, verbose_name="نام")),
                ("body", models.TextField(verbose_name="دیدگاه")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=False)),
                (
                    "post",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Comments",
                        to="postapp.pin_post",
                        verbose_name="پین",
                    ),
                ),
                (
                    "reply",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="postapp.askformovie",
                        verbose_name="پاسخ ها",
                    ),
                ),
            ],
            options={
                "verbose_name": "درخواست فیلم و سریال",
                "verbose_name_plural": " درخواست ها",
            },
        ),
    ]
